name: CAPE
on:
    push:
        branches: [$default-branch]
    pull_request:

jobs:
    python:
        name: Python
        uses: cape-ph/.github/.github/workflows/python_checks.yml@v1
        with:
            pytest: false # Enable to run `pytest` based tests
    general:
        name: General
        uses: cape-ph/.github/.github/workflows/general_checks.yml@v1
