name: Release

on:
    push:
        branches: [main]
    pull_request_target:
        types: [opened, edited, synchronize]

permissions:
    contents: write
    pull-requests: write

jobs:
    Release:
        uses: cape-ph/.github/.github/workflows/semantic_release.yml@v1
        secrets: inherit
        with:
            is_production: ${{ github.event_name == 'push' }}
