name: General Checks

on:
    workflow_call:

jobs:
    typos:
        name: Spell Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: crate-ci/typos@master
