name: Python Checks

on:
    workflow_call:
        inputs:
            python_version:
                description: "Python version to use"
                default: "3.11"
                required: false
                type: string
            pytest:
                description: "Enable pytest testing"
                default: false
                required: false
                type: boolean

jobs:
    lsp:
        name: Types (pyright)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              id: setup_python
              with:
                  python-version: ${{ inputs.python_version }}
                  cache: "pip"
                  cache-dependency-path: requirements.txt
            - name: install dependencies
              run: pip install -r requirements.txt
            - name: run pyright
              uses: jakebailey/pyright-action@v2
              with:
                  python-version: ${{ steps.setup_python.outputs.python-version }}
    black:
        name: Formatting (black)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: psf/black@stable
    isort:
        name: Formatting (isort)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: isort/isort-action@v1
    test:
        name: Tests (pytest)
        needs:
            - lsp
        if: ${{ inputs.pytest }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              id: setup_python
              with:
                  python-version: ${{ inputs.python_version }}
                  cache: "pip"
                  cache-dependency-path: requirements.txt
            - name: install dependencies
              run: pip install -r requirements.txt
            - name: run tests
              run: pytest --junitxml=junit/test-results-${{ steps.setup_python.outputs.python-version }}.xml
            - name: upload pytest results
              uses: actions/upload-artifact@v4
              with:
                  name: pytest-results-${{ steps.setup_python.outputs.python-version }}
                  path: junit/test-results-${{ steps.setup_python.outputs.python-version }}.xml
